apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gate
  name: gate
spec:
  ports:
  - name: minecraft
    nodePort: 32556
    port: 25565
    protocol: TCP
    targetPort: minecraft
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/name: gate
  type: NodePort
